# Generated by Django 4.2.3 on 2024-08-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
