# Generated by Django 4.2.3 on 2024-08-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sort',
            new_name='name',
        ),
    ]
